@Context_HostAddress = http://localhost:5059
@Context_Resource = contexts

###

GET {{Context_HostAddress}}/{{Context_Resource}}/singleton
Accept: application/json

###

GET {{Context_HostAddress}}/{{Context_Resource}}/scoped
Accept: application/json

###

GET {{Context_HostAddress}}/{{Context_Resource}}/transient
Accept: application/json

###
